/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proman1;

/**
 *
 * @author MC03353
 */
public class Frame extends javax.swing.JFrame {
        
    /**
     * Creates new form Frame
     */
    public Frame() {
        //creates the form and displays it 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField2 = new java.awt.TextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        textField5 = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        textField7 = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        list2 = new java.awt.List();
        list3 = new java.awt.List();
        jLabel5 = new javax.swing.JLabel();
        textField8 = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        mainPanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        lClientName = new java.awt.Label();
        lProjectPrice = new java.awt.Label();
        String sProjectName = null;
        tFProjectName = new java.awt.TextField();
        tFClientName = new java.awt.TextField();
        tFProjectPrice = new java.awt.TextField();
        java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("mm/dd/yy");
        jFTDate = new javax.swing.JFormattedTextField(format);
        jLProjectDeadline = new javax.swing.JLabel();
        rBApp = new javax.swing.JRadioButton();
        jLProjectType = new javax.swing.JLabel();
        rBGame = new javax.swing.JRadioButton();
        rBWebsite = new javax.swing.JRadioButton();
        jPApp = new javax.swing.JPanel();
        jLProjectType1 = new javax.swing.JLabel();
        rbAndroid = new javax.swing.JRadioButton();
        rBIos = new javax.swing.JRadioButton();
        rbOther = new javax.swing.JRadioButton();
        jPGame = new javax.swing.JPanel();
        tFPlatform = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tFGenre = new java.awt.TextField();
        jPWebsite = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tFServerAddress = new java.awt.TextField();
        tFNumberPages = new java.awt.TextField();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        btnAddProject = new java.awt.Button();
        btnCollate = new java.awt.Button();
        comboBox = new java.awt.Choice();
        jLProjectDeadline1 = new javax.swing.JLabel();
        java.awt.Label lTitle = new java.awt.Label();

        textField2.setText("textField1");

        textField5.setText("textField1");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Platform");

        textField7.setText("Enter Platform");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Genre");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Genre");

        textField8.setText("Enter Platform");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Platform");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Enter a Project Name:");

        lClientName.setText("Enter a Client Name:");

        lProjectPrice.setText("Enter Project Price (£):");

        tFProjectName.setName(""); // NOI18N
        tFProjectName.setText("Enter a project name");
        tFProjectName.setText("");
        tFProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFProjectNameActionPerformed(evt);
            }
        });

        tFClientName.setText("");
        tFClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFClientNameActionPerformed(evt);
            }
        });

        tFProjectPrice.setText("");
        tFProjectPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFProjectPriceActionPerformed(evt);
            }
        });

        jFTDate.setText(GetAndSet.getDate()+"");
        jFTDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTDateActionPerformed(evt);
            }
        });
        jFTDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFTDateKeyPressed(evt);
            }
        });

        jLProjectDeadline.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLProjectDeadline.setText("Enter Project Deadline:");
        jLProjectDeadline.setToolTipText("");
        jLProjectDeadline.setName(""); // NOI18N

        buttonGroup1.add(rBApp);
        rBApp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rBApp.setText("App");
        rBApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBAppActionPerformed(evt);
            }
        });

        jLProjectType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLProjectType.setText("Enter Project Type:");
        jLProjectType.setToolTipText("");
        jLProjectType.setName(""); // NOI18N

        buttonGroup1.add(rBGame);
        rBGame.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rBGame.setText("Game");
        rBGame.setActionCommand("");
        rBGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBGameActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBWebsite);
        rBWebsite.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rBWebsite.setText("Website");
        rBWebsite.setActionCommand("");
        rBWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBWebsiteActionPerformed(evt);
            }
        });

        jPApp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "App", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPApp.setEnabled(false);
        jPApp.setMinimumSize(new java.awt.Dimension(163, 230));
        jPApp.setPreferredSize(new java.awt.Dimension(163, 230));

        jLProjectType1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLProjectType1.setText("Platform:");
        jLProjectType1.setToolTipText("");
        jLProjectType1.setName(""); // NOI18N

        buttonGroup2.add(rbAndroid);
        rbAndroid.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbAndroid.setText("Android");
        rbAndroid.setActionCommand("");
        rbAndroid.setEnabled(false);
        rbAndroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAndroidActionPerformed(evt);
            }
        });

        buttonGroup2.add(rBIos);
        rBIos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rBIos.setText("iOS");
        rBIos.setEnabled(false);
        rBIos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBIosActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbOther);
        rbOther.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbOther.setText("Other");
        rbOther.setActionCommand("");
        rbOther.setEnabled(false);
        rbOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOtherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAppLayout = new javax.swing.GroupLayout(jPApp);
        jPApp.setLayout(jPAppLayout);
        jPAppLayout.setHorizontalGroup(
            jPAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAppLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOther)
                    .addComponent(rbAndroid)
                    .addComponent(rBIos)
                    .addComponent(jLProjectType1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAppLayout.setVerticalGroup(
            jPAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLProjectType1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBIos)
                .addGap(18, 18, 18)
                .addComponent(rbAndroid)
                .addGap(18, 18, 18)
                .addComponent(rbOther)
                .addGap(56, 56, 56))
        );

        jPGame.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Game", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPGame.setEnabled(false);
        jPGame.setMinimumSize(new java.awt.Dimension(163, 230));

        tFPlatform.setEnabled(false);
        tFPlatform.setText("Enter Platform");
        tFPlatform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFPlatformActionPerformed(evt);
            }
        });
        tFPlatform.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFPlatformFocusLost(evt);
            }
        });
        tFPlatform.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tFPlatformKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Platform:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Genre:");

        tFGenre.setEnabled(false);
        tFGenre.setText("Enter Genre");
        tFGenre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFGenreFocusLost(evt);
            }
        });
        tFGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFGenreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGameLayout = new javax.swing.GroupLayout(jPGame);
        jPGame.setLayout(jPGameLayout);
        jPGameLayout.setHorizontalGroup(
            jPGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFPlatform, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addGroup(jPGameLayout.createSequentialGroup()
                        .addGroup(jPGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tFGenre, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPGameLayout.setVerticalGroup(
            jPGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tFPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tFGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPWebsite.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Website", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPWebsite.setEnabled(false);
        jPWebsite.setMinimumSize(new java.awt.Dimension(163, 230));
        jPWebsite.setPreferredSize(new java.awt.Dimension(163, 230));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Number of Pages:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Server Name:");

        tFServerAddress.setEnabled(false);
        tFServerAddress.setText("Enter Address");
        tFServerAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFServerAddressFocusLost(evt);
            }
        });
        tFServerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFServerAddressActionPerformed(evt);
            }
        });

        tFNumberPages.setEnabled(false);
        tFNumberPages.setText("Enter a number");
        tFNumberPages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFNumberPagesFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPWebsiteLayout = new javax.swing.GroupLayout(jPWebsite);
        jPWebsite.setLayout(jPWebsiteLayout);
        jPWebsiteLayout.setHorizontalGroup(
            jPWebsiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPWebsiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPWebsiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFServerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPWebsiteLayout.createSequentialGroup()
                        .addGroup(jPWebsiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(tFNumberPages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPWebsiteLayout.setVerticalGroup(
            jPWebsiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPWebsiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tFServerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tFNumberPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        label2.setText("Project Details:");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextAreaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea);

        button1.setLabel("Quit");
        button1.setName(""); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("Clear");
        button2.setName(""); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        btnAddProject.setLabel("Add Project");
        btnAddProject.setName(""); // NOI18N
        btnAddProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProjectActionPerformed(evt);
            }
        });

        btnCollate.setLabel("Collate");
        btnCollate.setName(""); // NOI18N
        btnCollate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollateActionPerformed(evt);
            }
        });

        comboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboBoxFocusGained(evt);
            }
        });

        jLProjectDeadline1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLProjectDeadline1.setText("Enter Project Deadline:");
        jLProjectDeadline1.setToolTipText("");
        jLProjectDeadline1.setName(""); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jPApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLProjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(rBApp)
                                        .addGap(18, 18, 18)
                                        .addComponent(rBGame)
                                        .addGap(18, 18, 18)
                                        .addComponent(rBWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCollate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLProjectDeadline1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(lProjectPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tFProjectPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(lClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tFClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tFProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13)
                        .addComponent(jLProjectDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTDate))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLProjectDeadline1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFProjectName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLProjectDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tFClientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLProjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lProjectPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFProjectPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rBApp)
                        .addComponent(rBGame)
                        .addComponent(rBWebsite)))
                .addGap(28, 28, 28)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCollate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label1.getAccessibleContext().setAccessibleName("lProjectName");
        jLProjectType.getAccessibleContext().setAccessibleName("Project Type: ");
        label2.getAccessibleContext().setAccessibleName("Project Details");
        jLProjectDeadline1.getAccessibleContext().setAccessibleName("Load Existing Project");

        lTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lTitle.setText("ProManager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //if the App radio button is selected, allows access to panel and contents
    void rBAppTrue(){
        jPApp.setEnabled(true);
        rBIos.setEnabled(true);
        rbAndroid.setEnabled(true);
        rbOther.setEnabled(true);
    }
    
    //if the App radio button isn't selected, stops access to panel and contents    
    void rBAppFalse(){
        jPApp.setEnabled(false);
        rBIos.setEnabled(false);
        rbAndroid.setEnabled(false);
        rbOther.setEnabled(false);
    }
    
    //if the Game radio button is selected, allows access to panel and contents
    void rBGameTrue(){
        jPGame.setEnabled(true);
        tFPlatform.setEnabled(true);
        tFGenre.setEnabled(true);
    }
    
    //if the Game radio button isn't selected, stops access to panel and contents 
    void rBGameFalse(){
        jPGame.setEnabled(false);
        tFPlatform.setEnabled(false);
        tFGenre.setEnabled(false);      
    }
    
    //if the Website radio button is selected, allows access to panel and contents
    void rBWebsiteTrue(){
        jPWebsite.setEnabled(true);
        tFServerAddress.setEnabled(true);
        tFNumberPages.setEnabled(true);
    }
    
    //if the Website radio button is selected, allows access to panel and contents
    void rBWebsiteFalse(){
        jPWebsite.setEnabled(false);
        tFServerAddress.setEnabled(false);
        tFNumberPages.setEnabled(false);
    }
    
    //sets the project type to App
    private void rBAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBAppActionPerformed
        if(rBApp.isSelected()){
            GetAndSet.setProjectType("App");
            rBAppTrue();
            rBGameFalse();
            rBWebsiteFalse();
        }
    }//GEN-LAST:event_rBAppActionPerformed

    //sets the project type to Game
    private void rBGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBGameActionPerformed
        if(rBGame.isSelected()){
            GetAndSet.setProjectType("Game");
            rBAppFalse();
            rBGameTrue();
            rBWebsiteFalse();
        }
    }//GEN-LAST:event_rBGameActionPerformed

    //sets the project type to Website
    private void rBWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBWebsiteActionPerformed
        if(rBWebsite.isSelected()){
            GetAndSet.setProjectType("Website");
            rBAppFalse();
            rBGameFalse();
            rBWebsiteTrue();
        }
    }//GEN-LAST:event_rBWebsiteActionPerformed
    
    //sets the project to iOS App
    void iOSRadioBtn(){
        GetAndSet.setPlatform("iOS App");
    }
    
    //sets the project to Android App    
    void androidRadioBtn(){
        GetAndSet.setPlatform("Android App");
    }
    
    //sets the project to other     
    void otherRadioBtn(){
        GetAndSet.setPlatform("Other");
    }
    
    //event listener which calls the androidRadioBtn method when clicked
    private void rbAndroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAndroidActionPerformed
        androidRadioBtn();
    }//GEN-LAST:event_rbAndroidActionPerformed

    //event listener which calls the IosRadioBtn method when clicked
    private void rBIosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBIosActionPerformed
        iOSRadioBtn();
        
    }//GEN-LAST:event_rBIosActionPerformed

    //event listener which calls the otherRadioBtn method when clicked
    private void rbOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOtherActionPerformed
        otherRadioBtn();
    }//GEN-LAST:event_rbOtherActionPerformed

    //unused pregenerated code
    private void tFProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFProjectNameActionPerformed
        
    }//GEN-LAST:event_tFProjectNameActionPerformed

    //unused pregenerated code
    private void jFTDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTDateActionPerformed
        
    }//GEN-LAST:event_jFTDateActionPerformed

    //event listener which calls the jTextArea method
    private void jTextAreaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextAreaPropertyChange
        jTextArea();
    }//GEN-LAST:event_jTextAreaPropertyChange
    
    //sets jTextArea to blank initially
    private void jTextArea(){
        jTextArea.setText("Project Title: \n"
                    + "Date: \n"
                    + "Project Price: £\n"
                    + "Client Name: \n"
                    + "Project Type: \n"
                    + "Additional Information: ");
        jTextArea.setLineWrap(true);
        jTextArea.setWrapStyleWord(true);
    }
    
    private void clearFields(){
        
    }
    
    private void tFClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFClientNameActionPerformed

    }//GEN-LAST:event_tFClientNameActionPerformed
    
    //sets and updates the Text area with project details 
    private void btnCollateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollateActionPerformed
        GetAndSet.setProjectName(tFProjectName.getText());
        GetAndSet.setClientName(tFClientName.getText());
        
        if(rBApp.isSelected()){
            GetAndSet.setAddInfo("  Platform " + GetAndSet.getPlatform());
        }

        if(rBGame.isSelected()){
            GetAndSet.setAddInfo("  Game Details " + GetAndSet.getGame());
        }

        if(rBWebsite.isSelected()){
            GetAndSet.setAddInfo("  Website Information " + GetAndSet.getWebsite());
        }
        
        jTextArea.setText("Project Title: " + tFProjectName.getText() + "\n"
                + "Date: " + GetAndSet.getDate() + "\n"
                + "Project Price £" + tFProjectPrice.getText() + "\n"
                + "Client Name: " + tFClientName.getText() + "\n"
                + "Project Type: " + GetAndSet.getProjectType() + "\n"
                + "Additional Information:\n"
                + GetAndSet.getAddInfo());
        
        GetAndSet.updateArray();
    }//GEN-LAST:event_btnCollateActionPerformed

    private void tFProjectPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFProjectPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFProjectPriceActionPerformed

    private void tFPlatformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFPlatformActionPerformed
    
    }//GEN-LAST:event_tFPlatformActionPerformed

    private void tFGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFGenreActionPerformed

    //sets the setGame variable
    private void tFPlatformFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFPlatformFocusLost
        GetAndSet.setGame(tFPlatform.getText(),tFGenre.getText());
    }//GEN-LAST:event_tFPlatformFocusLost

    private void tFGenreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFGenreFocusLost
        GetAndSet.setGame(tFPlatform.getText(),tFGenre.getText());
    }//GEN-LAST:event_tFGenreFocusLost

    private void tFPlatformKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFPlatformKeyPressed
        
    }//GEN-LAST:event_tFPlatformKeyPressed

    private void tFServerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFServerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFServerAddressActionPerformed

    //exits the system
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        jTextArea();
    }//GEN-LAST:event_button2ActionPerformed

//    adds current projects to an array so the drop down box can be used
    private void btnAddProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProjectActionPerformed
        GetAndSet.setArray();
        GetAndSet.updateArray();
        GetAndSet.getArray();
    }//GEN-LAST:event_btnAddProjectActionPerformed

    private void jFTDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTDateKeyPressed
        
    }//GEN-LAST:event_jFTDateKeyPressed

    private void tFServerAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFServerAddressFocusLost
        GetAndSet.setWebsite(tFServerAddress.getText(),tFNumberPages.getText());
    }//GEN-LAST:event_tFServerAddressFocusLost

    private void tFNumberPagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFNumberPagesFocusLost
        GetAndSet.setWebsite(tFServerAddress.getText(),tFNumberPages.getText());
    }//GEN-LAST:event_tFNumberPagesFocusLost

//    logic to update the array contents and comboBox
    private void comboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxFocusGained
        int iCounter = 0;
        String comboBoxContents; 
        
        for(int i = 0; i < GetAndSet.updateArray() ;i++){
            comboBoxContents = GetAndSet.getArray()[iCounter];
            comboBox.addItem(comboBoxContents);
            iCounter++;
        }
        
        
    }//GEN-LAST:event_comboBoxFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAddProject;
    private java.awt.Button btnCollate;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Choice comboBox;
    private javax.swing.JFormattedTextField jFTDate;
    private javax.swing.JLabel jLProjectDeadline;
    private javax.swing.JLabel jLProjectDeadline1;
    private javax.swing.JLabel jLProjectType;
    private javax.swing.JLabel jLProjectType1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPApp;
    private javax.swing.JPanel jPGame;
    private javax.swing.JPanel jPWebsite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private java.awt.Label lClientName;
    private java.awt.Label lProjectPrice;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.List list2;
    private java.awt.List list3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton rBApp;
    private javax.swing.JRadioButton rBGame;
    private javax.swing.JRadioButton rBIos;
    private javax.swing.JRadioButton rBWebsite;
    private javax.swing.JRadioButton rbAndroid;
    private javax.swing.JRadioButton rbOther;
    private java.awt.TextField tFClientName;
    private java.awt.TextField tFGenre;
    private java.awt.TextField tFNumberPages;
    private java.awt.TextField tFPlatform;
    private java.awt.TextField tFProjectName;
    private java.awt.TextField tFProjectPrice;
    private java.awt.TextField tFServerAddress;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField5;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    // End of variables declaration//GEN-END:variables
}
